// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package _sysutils.actions;

import java.util.HashMap;
import com.mendix.core.objectmanagement.DataValidationInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Get member name in a type-safe way.
 * Before calling this action get an instance of the entity and create a Validation Feedback on the needed member with the formatted messsage: {1}
 * and the format parameter:
 * getKey(_SysUtils.Enum_GetMemberName_Parameter.validation_message_on_the_desired_object_member)
 * 
 * The validation used to detect the member name is deleted before returning the result.
 */
public class GetMemberName extends UserAction<java.lang.String>
{
	private final IMendixObject objectWithFeedbackAssigned;
	private final _sysutils.proxies.Enum_GetMemberName_Parameter feedbackMessageAssigned;

	public GetMemberName(
		IContext context,
		IMendixObject _objectWithFeedbackAssigned,
		java.lang.String _feedbackMessageAssigned
	)
	{
		super(context);
		this.objectWithFeedbackAssigned = _objectWithFeedbackAssigned;
		this.feedbackMessageAssigned = _feedbackMessageAssigned == null ? null : _sysutils.proxies.Enum_GetMemberName_Parameter.valueOf(_feedbackMessageAssigned);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        IContext context = getContext();
        String memberName = null;
        final IMendixIdentifier structuredMxId = objectWithFeedbackAssigned.getId();
        long longMxId = structuredMxId.toLong();
        for (DataValidationInfo dvi : context.getDataValidationList()) {
            if (longMxId == dvi.guid()) {
                final HashMap<String, String> errorFields = dvi.errorFields();
                for (
                    var itErrorFields = errorFields.entrySet().iterator();
                    itErrorFields.hasNext();) {
                    var pair = itErrorFields.next();
                    String message = pair.getValue();
                    if (feedbackMessageAssigned.name().equals(message)) {
                        if (memberName != null) {
                            throw new Exception(
                                "Object " + structuredMxId
                                    + " has more than one validation message: "
                                    + feedbackMessageAssigned.name());
                        }
                        memberName = pair.getKey();
                        itErrorFields.remove();
                    }
                }
            }
        }
        if (memberName == null) {
            throw new Exception(
                "Object " + structuredMxId + " has zero validation messages: "
                    + feedbackMessageAssigned.name());
        }

        return memberName;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetMemberName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
