// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package _sysutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import _sysutils.proxies.Enum_GetMemberName_Parameter;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * like getOriginalValueAsString but returns the actual value and it can also return empty and for references it returns comma-separated list of numbers
 */
public class GetMemberValueAsString2 extends UserAction<java.lang.String>
{
	private final IMendixObject obj;
	private final _sysutils.proxies.Enum_GetMemberName_Parameter memberFeedbackMessage;

	public GetMemberValueAsString2(
		IContext context,
		IMendixObject _obj,
		java.lang.String _memberFeedbackMessage
	)
	{
		super(context);
		this.obj = _obj;
		this.memberFeedbackMessage = _memberFeedbackMessage == null ? null : _sysutils.proxies.Enum_GetMemberName_Parameter.valueOf(_memberFeedbackMessage);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        final IContext context = getContext();

        final IMendixObjectMember<?> srcMember =
            getMember(obj, memberFeedbackMessage);

        final String memberName = srcMember.getName();
        return GetMemberValueAsString.getMemberValueAsString(context, obj, memberName);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetMemberValueAsString2";
	}

	// BEGIN EXTRA CODE

    private IMendixObjectMember<?> getMember(
            final IMendixObject obj,
            final Enum_GetMemberName_Parameter magicEnum) throws Exception {
        final IContext context = getContext();
        final String memberName = new GetMemberName(context, obj, magicEnum.name()).execute();

        final IMendixObjectMember<?> member = obj.getMember(context, memberName);
        return member;
    }

	// END EXTRA CODE
}
